name: Build docker-image-arm64

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
     inputs:
      image_tag:
        description: ''
        required: true
    

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: birdxs/iptables-web 

      - name: Docker Setup QEMU
        # You may pin to the exact commit or the version.
        # uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        uses: docker/setup-qemu-action@v2
        with:
          # QEMU static binaries Docker image (e.g. tonistiigi/binfmt:latest)
          image: tonistiigi/binfmt:latest
          # Platforms to install (e.g. arm64,riscv64,arm)
          # platforms: arm64
          platforms: all
          
      - name: Build and push Docker image
        run: |
              
              docker buildx create --use
              docker buildx build --platform linux/arm64 \
                      -t birdxs/iptables-web-arm64:1.8.4 \
                      --push \
                      -f ./Dockerfile .
